### ISSUE TITLE
Ability to specify the amount of padding

### ISSUE THREAD

**Issue by jeremylorino** [mkhira2/shadowizard#1]
Right now per the options one can specify whether padding is applied or not. I would like to able to additionally specify how much padding.

Example uses:

```javascript
shadowizard({
    padding: 12
});
```
```javascript
shadowizard({
    padding: "12px"
});
```
```javascript
shadowizard({
    padding: false
});
```
```javascript
shadowizard({
    padding: true
});
```

**Comment by mkhira2** [comment]
This is done in v1.0.2. Thank you for helping make kenji_shadowizard the greatest npm package of all time!

**Comment by jeremylorino** [comment]
Greatest package ever
